#!/bin/bash

brew tap caskroom/cask
brew tap caskroom/versions

apps=(
  1password
  alfred
  appcleaner
  caffeine
  chefdk
  cyberduck
  dropbox
  goofy
  google-chrome
  google-drive
  hipchat
  iterm2-beta
  java
  macid
  rescuetime
  sequel-pro
  silverlight
  skype
  spotify
  teamviewer
  utorrent
  vlc
)

brew cask install --appdir="/Applications" ${apps[@]}
brew cleanup
