#!/bin/zsh
#
set -e
ROOT=${1:-~}

function main {
  test -d "$ROOT/.config" || mkdir -p "$ROOT/.config"
  install_packages
  setup_vim
  setup_tmux
  setup_ssh
}

function setup_ssh {
  TARGET=$ROOT/${2:-.ssh}
  ln -nfs $ROOT/Dropbox\ \(Personlig\)/Apps\ Sync/Dotfiles/ssh $TARGET
}

function setup_tmux {
  TPM_DIR="tmux/dottmux/plugins/tpm"
  if [ ! -d "$TPM_DIR" ]; then
    git clone https://github.com/tmux-plugins/tpm $TPM_DIR
    echo "Hit prefix + I to install TMUX plugins"
  fi
}

function setup_vim {
  VUNDLE_DIR="vim/dotvim/bundle/Vundle.vim"
  if [ ! -d "$VUNDLE_DIR" ]; then
    git clone https://github.com/VundleVim/Vundle.vim.git $VUNDLE_DIR
    vim +PluginInstall +qall
  fi
}

function install_packages {
  install "ag/agignore" ".agignore"
  install "git/gitconfig" ".gitconfig"
  install "git/gitmessage" ".gitmessage"
  install "git/gitignore_global" ".gitignore_global"
  install "grunt"
  install "tmux/tmux.conf" ".tmux.conf"
  install "tmux/dottmux" ".tmux"
  install "vim/vimrc" ".vimrc"
  install "vim/gvimrc" ".gvimrc"
  install "vim/dotvim" ".vim"
  install "zsh/oh-my-zsh/" ".oh-my-zsh"
  install "zsh/extensions/plugins/mathiasjakobsen" ".oh-my-zsh/plugins/mathiasjakobsen"
  install "zsh/extensions/themes/mathiasjakobsen.zsh-theme" ".oh-my-zsh/themes/mathiasjakobsen.zsh-theme"
  install "zsh/extensions/themes/honukai.zsh-theme" ".oh-my-zsh/themes/honukai.zsh-theme"
  install "zsh/zshrc" ".zshrc"
  install "zsh/zshenv" ".zshenv"
  install "zsh/profile" ".profile"
  install "bin" "bin"
}
function install() {
  TARGET=$ROOT/${2:-.$1}
  if [[ -e $TARGET ]]; then
    rm -rf $TARGET
  fi
  ln -nfs $PWD/$1 $TARGET
}

main
