#!/bin/zsh
#
set -e
ROOT=${1:-~}

function main {
  test -d "$ROOT/.config" || mkdir -p "$ROOT/.config"
  install_rvm
  setup_vim
  setup_tmux
  setup_zsh
  setup_oh_my_zsh
  setup_theme
  install_packages
  install_flynn
}

function install_rvm {
  if [ ! type "rvm" ]; then
    gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
    \curl -sSL https://get.rvm.io | bash -s stable --ruby
  fi
}

function install_flynn {
  L=/usr/local/bin/flynn && curl -sSL -A "`uname -sp`" https://dl.flynn.io/cli | zcat >$L && chmod +x $L
}

function setup_oh_my_zsh {
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
}

function setup_theme {
  yarn global add pure-prompt
  open "Snazzy.itermcolors"
}

function setup_zsh {
  if ! type "/usr/local/bin/zsh" > /dev/null; then
    brew install zsh
  fi

  local shell_path;
  shell_path="$(which zsh)"

  if ! grep "$shell_path" /etc/shells > /dev/null 2>&1 ; then
    echo "Adding '$shell_path' to /etc/shells"
    sudo sh -c "echo $shell_path >> /etc/shells"
  fi

  chsh -s "$shell_path"
}

function setup_tmux {
  TPM_DIR="tmux/dottmux/plugins/tpm"
  if [ ! -d "$TPM_DIR" ]; then
    git clone https://github.com/tmux-plugins/tpm $TPM_DIR
    echo "Hit prefix + I to install TMUX plugins"
  fi
}

function setup_vim {
  VUNDLE_DIR="vim/dotvim/bundle/Vundle.vim"
  if [ ! -d "$VUNDLE_DIR" ]; then
    git clone https://github.com/VundleVim/Vundle.vim.git $VUNDLE_DIR
    vim +PluginInstall +qall
  fi
}

function install_packages {
  DOTFILES="dotfiles"
  symlink "$DOTFILES/ag/agignore" ".agignore"
  symlink "$DOTFILES/git/gitconfig" ".gitconfig"
  symlink "$DOTFILES/git/gitmessage" ".gitmessage"
  symlink "$DOTFILES/git/gitignore_global" ".gitignore_global"
  symlink "$DOTFILES/tmux/tmux.conf" ".tmux.conf"
  symlink "$DOTFILES/tmux/dottmux" ".tmux"
  symlink "$DOTFILES/vim/vimrc" ".vimrc"
  symlink "$DOTFILES/vim/gvimrc" ".gvimrc"
  symlink "$DOTFILES/vim" ".vim"
  symlink "$DOTFILES/zsh/extensions/plugins/mathiasjakobsen" ".oh-my-zsh/plugins/mathiasjakobsen"
  symlink "$DOTFILES/zsh/extensions/themes/mathiasjakobsen.zsh-theme" ".oh-my-zsh/themes/mathiasjakobsen.zsh-theme"
  symlink "$DOTFILES/zsh/extensions/themes/honukai.zsh-theme" ".oh-my-zsh/themes/honukai.zsh-theme"
  symlink "$DOTFILES/zsh/zshrc" ".zshrc"
  symlink "$DOTFILES/zsh/zshenv" ".zshenv"
  symlink "$DOTFILES/zsh/profile" ".profile"
  symlink "$DOTFILES/bin" "bin"
  symlink "Google Drev/Apps Sync/Dotfiles/ssh" ".ssh"
  symlink "Google Drev/Apps Sync/Dotfiles/zsh_history" ".zsh_history"
}

function symlink() {
  TARGET=$ROOT/${2:-.$1}
  echo $TARGET
  if [[ -e $TARGET ]]; then
    rm -rf $TARGET
  fi
  ln -nfs $ROOT/$1 $TARGET
}

main
