#!/bin/zsh
#
set -e
ROOT=${1:-~}

function main {
  test -d "$ROOT/.config" || mkdir -p "$ROOT/.config"
  install_packages
  setup_vim
  setup_tmux
  setup_zsh
}

function setup_zsh {
  if ! type "/usr/local/bin/zsh" > /dev/null; then
    brew install zsh
  fi
  chsh -s /usr/local/bin/zsh $USER
  echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells
}

function setup_tmux {
  TPM_DIR="tmux/dottmux/plugins/tpm"
  if [ ! -d "$TPM_DIR" ]; then
    git clone https://github.com/tmux-plugins/tpm $TPM_DIR
    echo "Hit prefix + I to install TMUX plugins"
  fi
}

function setup_vim {
  VUNDLE_DIR="vim/dotvim/bundle/Vundle.vim"
  if [ ! -d "$VUNDLE_DIR" ]; then
    git clone https://github.com/VundleVim/Vundle.vim.git $VUNDLE_DIR
    vim +PluginInstall +qall
  fi
}

function install_packages {
  DOTFILES="dotfiles"
  symlink "$DOTFILES/ag/agignore" ".agignore"
  symlink "$DOTFILES/git/gitconfig" ".gitconfig"
  symlink "$DOTFILES/git/gitmessage" ".gitmessage"
  symlink "$DOTFILES/git/gitignore_global" ".gitignore_global"
  symlink "$DOTFILES/tmux/tmux.conf" ".tmux.conf"
  symlink "$DOTFILES/tmux/dottmux" ".tmux"
  symlink "$DOTFILES/vim/vimrc" ".vimrc"
  symlink "$DOTFILES/vim/gvimrc" ".gvimrc"
  symlink "$DOTFILES/vim/dotvim" ".vim"
  symlink "$DOTFILES/zsh/oh-my-zsh/" ".oh-my-zsh"
  symlink "$DOTFILES/zsh/extensions/plugins/mathiasjakobsen" ".oh-my-zsh/plugins/mathiasjakobsen"
  symlink "$DOTFILES/zsh/extensions/themes/mathiasjakobsen.zsh-theme" ".oh-my-zsh/themes/mathiasjakobsen.zsh-theme"
  symlink "$DOTFILES/zsh/extensions/themes/honukai.zsh-theme" ".oh-my-zsh/themes/honukai.zsh-theme"
  symlink "$DOTFILES/zsh/zshrc" ".zshrc"
  symlink "$DOTFILES/zsh/zshenv" ".zshenv"
  symlink "$DOTFILES/zsh/profile" ".profile"
  symlink "$DOTFILES/bin" "bin"
  symlink "Dropbox (Personlig)/Apps Sync/Dotfiles/ssh" ".ssh"
}

function symlink() {
  TARGET=$ROOT/${2:-.$1}
  echo $TARGET
  if [[ -e $TARGET ]]; then
    rm -rf $TARGET
  fi
  ln -nfs $ROOT/$1 $TARGET
}

main
