#!/usr/bin/env bash

# Mostly hijacked from https://mths.be/osx

# ----------------------------------------------------------------------------------
# Mail.app
# ----------------------------------------------------------------------------------

# Send mail using ⌘ +Enter
defaults write com.apple.mail NSUserKeyEquivalents -dict-add "@\U21a9" -string "@\U21a9"

# Sync all accounts using ⌘ +s
defaults write com.apple.mail NSUserKeyEquivalents -dict-add "Hent alle nye beskeder" -string "@s"

# Seach all accounts using ⌘ +l
defaults write com.apple.mail NSUserKeyEquivalents -dict-add "Søg i postkasse" -string "@l"

# ----------------------------------------------------------------------------------
# Trackpad, mouse, keyboard, Bluetooth accessories, and input
# ----------------------------------------------------------------------------------

# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 10
