" Vim graphical configuration.

set antialias                     " MacVim: smooth fonts
set encoding=utf-8                " Use UTF-8 everywhere
set guioptions-=T                 " Hide toolbar
set background=dark               " Background
set lines=60 columns=400          " Window dimensions
set guioptions-=r                 " Don't show right scrollbar
set guifont=Menlo\ Regular:h14    " Use 'Menlo' at 14px
