set nocompatible  " IMproved
filetype off

set rtp+=~/.vim/dotvim/bundle/Vundle.vim
set rtp+=/usr/local/opt/fzf

call vundle#begin()
  Plugin 'gmarik/Vundle.vim'            " Plugin Manager (required)
  Plugin 'vim-polyglot'                 " Polyglot syntax highlighting
  Plugin 'w0rp/ale'                     " Async polyglot linting
  Plugin 'tpope/vim-dispatch'           " Async Vim operations
  Plugin 'tpope/vim-endwise'            " Automatically close code blocks (i.e. add 'end' in Ruby)
  Plugin 'tpope/vim-fugitive'           " Git wrapper, with command like :Gblame, :Gmove & :Gstatus
  Plugin 'tpope/vim-rails'              " Ruby on Rails powers
  Plugin 'tpope/vim-surround'           " Change/remove surrounding marks
  Plugin 'tpope/vim-commentary'         " Use 'g a' to comment out anything, in any language
  Plugin 'itchyny/lightline.vim'        " Lightweight clone of 'Powerline'
  Plugin 'mattn/emmet-vim'              " (TODO) Mutate selection to HTML/code structure (i.e. a list -> ul with i elements)
  Plugin 'terryma/vim-expand-region'    " Use '+' and '_' to expend current selection (in visual mode)
  Plugin 'airblade/vim-gitgutter'       " Show git diff in the gutter
  Plugin 'myusuf3/numbers.vim'          " Show relative line numbers, in insert mode
  Plugin 'kien/rainbow_parentheses.vim' " Hightlight nested parentheses/brackets
  Plugin 'ervandew/supertab'            " Shuffle auto completion, only using <Tab>
  Plugin 'godlygeek/tabular'            " ':Tabularize/[char]' to auto align based on RegEx
  Plugin 'wakatime/vim-wakatime'        " Wakatime tracking
  Plugin 'janko-m/vim-test'             " Run polyglot tests
  Plugin 'AndrewRadev/linediff.vim'     " Compare two selection split view, by ':Linediff' each of them
  Plugin 'flazz/vim-colorschemes'       " Vim Color Collection
  Plugin 'takac/vim-hardtime'
call vundle#end()

filetype plugin indent on
syntax on

" colorscheme minimalist
let g:hardtime_default_on = 1

source ~/.vim/dotvim/core.vim
source ~/.vim/dotvim/keybindings.vim
source ~/.vim/dotvim/autocmd.vim
source ~/.vim/dotvim/silversearcher.vim
