# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="honukai"
export DISABLE_AUTO_TITLE="true"
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
plugins=(docker gem coffee tmux tmuxinator brew git battery osx rake ruby rvm mathiasjakobsen)
fpath=(/usr/local/share/zsh-completions $fpath)
source $ZSH/oh-my-zsh.sh

source $HOME/Dropbox\ \(Personlig\)/Apps\ Sync/Dotfiles/github_token.sh

export GOPATH=$HOME/Work/Go
echo "export SSH_AUTH_SOCK=$SSH_AUTH_SOCK" > ~/.auth_ssh

bindkey -v
bindkey '^R' history-incremental-pattern-search-backward
export DOCKER_HOST=tcp://localhost:4243


export NARWHAL_ENGINE=jsc

export PATH=$PATH:$GOPATH/bin
PATH="/usr/local/share/npm/bin:$PATH"
PATH="$HOME/bin:$PATH"
PATH=/usr/local/bin:$PATH:$HOME/.rvm/bin
export PATH="/usr/local/narwhal/bin:$PATH"
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
source $(brew --prefix php-version)/php-version.sh && php-version 5
source `brew --prefix`/etc/profile.d/z.sh

export CAPP_BUILD="/Users/mathiasjakobsen/Downloads/Starter/Build"


 #added by travis gem
[ -f /Users/mathiasjakobsen/.travis/travis.sh ] && source /Users/mathiasjakobsen/.travis/travis.sh

eval $(thefuck --alias)

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

